// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package apiserver

import (
	"github.com/hanzhuoxian/mall/internal/apiserver/config"
	"github.com/hanzhuoxian/mall/internal/apiserver/controller"
)

// Injectors from wire.go:

// initApiServer is the Wire injector. wire gen will generate wire_gen.go from this.
func initApiServer(cfg *config.Config) (*apiserver, error) {
	gracefulShutdown := provideGracefulShutdown()
	apiServer, err := provideAPIServer(cfg)
	if err != nil {
		return nil, err
	}
	userClient, err := provideUserClient(cfg)
	if err != nil {
		return nil, err
	}
	userController := controller.NewUserController(userClient)
	controllers := controller.NewControllers(userController)
	apiserverApiserver, err := newApiServer(gracefulShutdown, apiServer, controllers)
	if err != nil {
		return nil, err
	}
	return apiserverApiserver, nil
}
