// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package userserver

import (
	"github.com/hanzhuoxian/mall/internal/userserver/cache/redis"
	"github.com/hanzhuoxian/mall/internal/userserver/config"
	"github.com/hanzhuoxian/mall/internal/userserver/controller"
	"github.com/hanzhuoxian/mall/internal/userserver/store/mysql"
)

// Injectors from wire.go:

// initUserServer is the Wire injector. wire gen will generate wire_gen.go from this.
func initUserServer(cfg *config.Config) (*userServer, error) {
	gracefulShutdown := provideGracefulShutdown()
	apiServer, err := provideAPIServer(cfg)
	if err != nil {
		return nil, err
	}
	grpcServer := provideGRPCServer(cfg)
	mySQLOptions := provideMySQLOptions(cfg)
	factory, err := mysql.NewDatastore(mySQLOptions)
	if err != nil {
		return nil, err
	}
	redisOptions := provideRedisOptions(cfg)
	cacheFactory, err := redis.NewCachestore(redisOptions)
	if err != nil {
		return nil, err
	}
	userController := controller.NewUserController(cacheFactory)
	controllers := controller.NewControllers(userController)
	userserverUserServer := newUserServer(gracefulShutdown, apiServer, grpcServer, factory, cacheFactory, controllers)
	return userserverUserServer, nil
}
